### ISSUE TITLE
exque is not properly handling exceptions

### ISSUE THREAD

**Issue by travisdmathis** [localvore-today/exque#14]
08:57:56.879 [error] Process #PID<0.7344.0> raised an exception
** (Protocol.UndefinedError) protocol String.Chars not implemented for %Poison.SyntaxError{message: "Unexpected end of input at position 0", pos: nil, token: nil}
    (elixir) lib/string/chars.ex:3: String.Chars.impl_for!/1
    (elixir) lib/string/chars.ex:17: String.Chars.to_string/1
    (algolia_indexer) lib/algolia_indexer/consumers/merchant_message_processor.ex:2: AlgoliaIndexer.Consumers.MerchantMessageProcessor.consume/4

This error appears to be coming out of exque but this is just exque failing to handle the exception.

**Comment by joshleecreates** [comment]
Exque suppresses exceptions within consumers so that the consumed message can be nacked before the original error message is re-raised by exque ;)
